/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author solor
 */
public class Cuestionario extends javax.swing.JFrame {

    /**
     * Creates new form Cuestionario
     */
    FondoPanel fondo6=new FondoPanel();
    ButtonGroup g1,g2;
    conexion c;
    
    
    public Cuestionario() 
    {
        this.setContentPane(fondo6);
        initComponents();
        g1 = new ButtonGroup();
        g1.add(pregunta1_a);
        g1.add(pregunta1_b);
        g1.add(pregunta1_c);
        g1.add(pregunta1_d);
        
        g2 = new ButtonGroup();
        g2.add(pregunta2_a);
        g2.add(pregunta2_b);
        g2.add(pregunta2_c);
        g2.add(pregunta2_d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pregunta1_a = new javax.swing.JRadioButton();
        pregunta1_b = new javax.swing.JRadioButton();
        pregunta1_c = new javax.swing.JRadioButton();
        pregunta1_d = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pregunta2_a = new javax.swing.JRadioButton();
        pregunta2_b = new javax.swing.JRadioButton();
        pregunta2_c = new javax.swing.JRadioButton();
        pregunta2_d = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 115));

        jLabel1.setText("CONTESTE CON HONESTIDAD LAS SIGUIENTES PREGUNTAS");

        jLabel2.setText("¿Como es tu interacción en redes?");

        pregunta1_a.setText("A");

        pregunta1_b.setText("B");

        pregunta1_c.setText("C");
        pregunta1_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta1_cActionPerformed(evt);
            }
        });

        pregunta1_d.setText("D");
        pregunta1_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta1_dActionPerformed(evt);
            }
        });

        jLabel3.setText("Comparto memes en Facebook y otras redes");

        jLabel4.setText("Solo usa las redes para tareas de la escuela");

        jLabel5.setText("Mantengo conversaciones un poco agresivas con mis amigos/compañeros");

        jLabel6.setText("Me pongo a insultar y discutir en redes con Twitter");

        jLabel7.setText("Han compartido stickers mios");

        jLabel8.setText("Me llevo asi con mis compañeros y todos tenemos memes de el salon");

        jLabel9.setText("Han compartido stickers y memes con fotos mias");

        jLabel10.setText("Nunca lo he hecho ni me lo han hecho");

        jLabel11.setText("Te han hecho o has hecho memes y/o algun tipo de agresion similar");

        pregunta2_a.setText("A");

        pregunta2_b.setText("B");

        pregunta2_c.setText("C");
        pregunta2_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta2_cActionPerformed(evt);
            }
        });

        pregunta2_d.setText("D");
        pregunta2_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta2_dActionPerformed(evt);
            }
        });

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta1_c)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta1_b)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta1_a)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta1_d)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta2_a)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta2_c)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta2_b)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta2_d)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta1_a)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta1_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta1_c)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta1_d))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta2_a)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta2_b)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta2_c)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta2_d)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pregunta1_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta1_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta1_cActionPerformed

    private void pregunta1_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta1_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta1_dActionPerformed

    private void pregunta2_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta2_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta2_cActionPerformed

    private void pregunta2_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta2_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta2_dActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String opcion1="",opcion2="";
        c=new conexion();
        
        if(pregunta1_a.isSelected())
        {
            opcion1="A";
        }
        if(pregunta1_b.isSelected())
        {
            opcion1="B";
        }
        if(pregunta1_c.isSelected())
        {
            opcion1="C";
        }
        if(pregunta1_d.isSelected())
        {
            opcion1="D";
        }
        
        if(pregunta2_a.isSelected())
        {
            opcion2="A";
        }
        if(pregunta2_b.isSelected())
        {
            opcion2="B";
        }
        if(pregunta2_c.isSelected())
        {
            opcion2="C";
        }
        if(pregunta2_d.isSelected())
        {
            opcion2="D";
        }
        
        
        String sql ="insert into respuestas(id_alumno,respuestas) "
                + "values (1,'"+opcion1+"'),(1,'"+opcion2+"')";
       
        
        try
        {
            System.out.println(sql);
            c.proceso_tabla(sql);
            
        }
        catch(Exception e)
        {
            System.err.println("error en la insercion: "+ e.getMessage());
        }
        finally
        {
            c.cerrar();
        }
        
        this.setVisible(false);
        new Cuestionario2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton pregunta1_a;
    private javax.swing.JRadioButton pregunta1_b;
    private javax.swing.JRadioButton pregunta1_c;
    private javax.swing.JRadioButton pregunta1_d;
    private javax.swing.JRadioButton pregunta2_a;
    private javax.swing.JRadioButton pregunta2_b;
    private javax.swing.JRadioButton pregunta2_c;
    private javax.swing.JRadioButton pregunta2_d;
    // End of variables declaration//GEN-END:variables
        class FondoPanel extends JPanel
            {
                private Image imagen;
                
                @Override
                public void paint (Graphics g)
                {
                    imagen = new ImageIcon(getClass().getResource("/Imagenes/cuestionario.png")).getImage();
                    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                    setOpaque(false);
                    
                    super.paint(g);
                }
            }
}
