/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author solor
 */
public class Cuestionario2_Or extends javax.swing.JFrame {

    /**
     * Creates new form Cuestionario2
     */
    FondoPanel fondo7=new FondoPanel();
    ButtonGroup g1,g2,g3;
    conexion c;
    
    public Cuestionario2_Or() 
    {
        this.setContentPane(fondo7);
        initComponents();
        g1 = new ButtonGroup();
        g1.add(pregunta3_a);
        g1.add(pregunta3_b);
        
        g2 = new ButtonGroup();
        g2.add(pregunta4_a);
        g2.add(pregunta4_b);
        g2.add(pregunta4_c);
        g2.add(pregunta4_d);
        
        g3 = new ButtonGroup();
        g3.add(pregunta5_a);
        g3.add(pregunta5_b);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pregunta4_c = new javax.swing.JRadioButton();
        pregunta4_d = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pregunta3_a = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        pregunta3_b = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        pregunta4_a = new javax.swing.JRadioButton();
        pregunta4_b = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pregunta5_a = new javax.swing.JRadioButton();
        pregunta5_b = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 115));

        jPanel1.setLayout(null);

        jLabel3.setText("No, nunca me ha pasado");

        pregunta4_c.setText("C");
        pregunta4_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta4_cActionPerformed(evt);
            }
        });

        pregunta4_d.setText("D");
        pregunta4_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta4_dActionPerformed(evt);
            }
        });

        jLabel5.setText("Si, me ha pasado");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Redes sociales (Facebook, Twitter)");

        jLabel8.setText("No me han agredido nunca");

        jLabel2.setText("Te han llegado mensajes insultandote o humillandote");

        jLabel9.setText("Mesajeria directa (WhatsApp, Messenger)");

        pregunta3_a.setText("A");

        jLabel10.setText("Llamadas o videollamadas");

        pregunta3_b.setText("B");

        jLabel11.setText("Te han agredido por internet, si es asi en que tipo  ");

        pregunta4_a.setText("A");

        pregunta4_b.setText("B");

        jLabel4.setText("¿Te concideras agredido por redes sociales?");

        jLabel6.setText("No, nunca me ha pasado");

        pregunta5_a.setText("A");

        pregunta5_b.setText("B");

        jLabel12.setText("Si, me ha pasado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta3_b)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta3_a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta4_a)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta4_b)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta4_c)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta4_d)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta5_b)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pregunta5_a)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton1)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta3_a)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta3_b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta4_a)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta4_b)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta4_c)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta4_d)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pregunta5_a)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta5_b))))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pregunta4_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta4_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta4_cActionPerformed

    private void pregunta4_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta4_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta4_dActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String opcion1="",opcion2="",opcion3="";
        c=new conexion();
        
        if(pregunta3_a.isSelected())
        {
            opcion1="A";
        }
        if(pregunta3_b.isSelected())
        {
            opcion1="B";
        }
        
        if(pregunta4_a.isSelected())
        {
            opcion2="A";
        }
        if(pregunta4_b.isSelected())
        {
            opcion2="B";
        }
        if(pregunta4_c.isSelected())
        {
            opcion2="C";
        }
        if(pregunta4_d.isSelected())
        {
            opcion2="D";
        }
        
        if(pregunta5_a.isSelected())
        {
            opcion3="A";
        }
        if(pregunta5_b.isSelected())
        {
            opcion3="B";
        }
        
        
        
        String sql ="insert into respuestas_orientadores(id_orientador,respuestas) "
                + "values (1,'"+opcion1+"'),(1,'"+opcion2+"'),(1,'"+opcion3+"')";
       
        
        try
        {
            System.out.println(sql);
            c.proceso_tabla(sql);
            
        }
        catch(Exception e)
        {
            System.err.println("error en la insercion: "+ e.getMessage());
        }
        finally
        {
            c.cerrar();
        }
        this.setVisible(false);
        new Resultado_EncuestaOr().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuestionario2_Or.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuestionario2_Or.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuestionario2_Or.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuestionario2_Or.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cuestionario2_Or().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton pregunta3_a;
    private javax.swing.JRadioButton pregunta3_b;
    private javax.swing.JRadioButton pregunta4_a;
    private javax.swing.JRadioButton pregunta4_b;
    private javax.swing.JRadioButton pregunta4_c;
    private javax.swing.JRadioButton pregunta4_d;
    private javax.swing.JRadioButton pregunta5_a;
    private javax.swing.JRadioButton pregunta5_b;
    // End of variables declaration//GEN-END:variables
        class FondoPanel extends JPanel
            {
                private Image imagen;
                
                @Override
                public void paint (Graphics g)
                {
                    imagen = new ImageIcon(getClass().getResource("/Imagenes/cuestionario.png")).getImage();
                    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                    setOpaque(false);
                    
                    super.paint(g);
                }
            }
}
